### ISSUE TITLE
apt-get

### ISSUE THREAD

**Issue by rafaelcmrj** [tessel/t2-cli#1082]
why can't I run apt-get commands when logged in tessel as root ?

**Comment by HipsterBrown** [comment]
@rafaelcmrj This is a constraint of OpenWRT, the Linux distribution running on Tessel. Instead of `apt-get`, OpenWRT comes with a lightweight package manager built for this type of embedded operating system called [`opkg`](https://wiki.openwrt.org/doc/techref/opkg). It's the same reason why we don't have `npm` running on Tessel, the constrained amount of RAM. 

Closing because this is out of control of this project.
