### ISSUE TITLE
t2 run without package.json

### ISSUE THREAD

**Issue by LinusU** [tessel/t2-cli#284]
```text
$ cd /tmp
$ mkdir t2-testing
$ cd t2-testing
$ vim test.js
$ t2 run test.js
INFO Connecting to Tessel...
INFO Connected to Tessel-AAAAAAA over LAN
WARN Invalid project directory
$ echo $?
1
```

First of all, it's a bit misleading that it just prints `WARN` but still dies. I first thought that the issue was something else.

~~~I think that the problem is that `/tmp` is a symlink on OS X and thus~~~

Actually, I think that the problem is that I don't have a `package.json`, is that a requirement? I thought that `tessel run` worked with just one file if there wasn't a `package.json` available.

**Comment by Frijol** [comment]
I believe package.json is required (@tcr can you confirm?).
Does it work if you run `t2 init` in that folder first?

**Comment by rwaldron** [comment]
Yes, it is. I migrated this requirement from the t1 bundling process.

**Comment by johnnyman727** [comment]
Yes, you either need a `package.json` or a `node_modules` folder. Otherwise the CLI would continue traversing up the directory tree, trying to find the root node of the project.

**Comment by LinusU** [comment]
Maybe we could make it so that if a package.json file is absent, it would upload just that one file that it is pointed to?

**Comment by rwaldron** [comment]
I don't see why not. I'm pretty familiar with that bundling code and I think I could implement this fairly easily.

**Comment by rwaldron** [comment]
And it just occurred to me that this is almost the same as https://github.com/tessel/t2-cli/issues/272

**Comment by LinusU** [comment]
Cool, I think it's good to have both. That way we'll try to do the right thing but there is also a way to be explicit :)

**Comment by johnnyman727** [comment]
I don't think it's a good idea to have both. For instance, what if you are trying to run one of the example files in the examples subdirectory of a module? The CLI needs to traverse the tree in order to find the `package.json` and include the actual driver.

I think we should just stick with the `-s` option.

**Comment by LinusU** [comment]
I absolutely think it should traverse the file system to find the package.json file. It's only when it's not found, in any parent directory, that we should deploy only the file.

Maybe it would be a good idea to make it clear from the command output that only a single file is being sent thought.

Or maybe we just should improve the error message. But I think that it's nice to quickly be able to send a file over when you are testing things...

**Comment by johnnyman727** [comment]
Oh, yes! I agree 100% to that. And I definitely think it needs a warning along with it:
```
WARN: No package.json found, deploying only {FILE_NAME}
```

**Comment by rwaldron** [comment]
@johnnyman727 good call on the notice

**Comment by johnnyman727** [comment]
@rwaldron mind if I assign this to you since you're most familiar with bundling code now?

**Comment by wprater** [comment]
if there is no `package.json` nor a `node_modules` dir and you're trying to upload just this file, will it always go to `/app/` root?  otherwise, we'd have no way to tell where it would live in the apps tree?

**Comment by johnnyman727** [comment]
@wprater the deployment goes to a [different path depending on if it was `push`ed or `run`ed](https://github.com/tessel/t2-cli/blob/master/lib/tessel/deploy.js#L9-L10). I think it should just be the only file in the appropriate directory.

One other note, is that we'll have to add a new file that specifies how to run the project when it's pushed. As it is, we [read a file](https://github.com/tessel/t2-cli/blob/master/lib/tessel/deploy.js#L315) that specifies [how the project is started](https://github.com/tessel/t2-cli/blob/master/resources/start_node_script.sh). This is so that it's easy for OpenWRT to start the service on boot.

**Comment by wprater** [comment]
@johnnyman727 so it's expecting an `index.js` or a `main` property on the `package.json`.

I undersand the different paths, but if we're just to push a single file and there is no notion of a project root, how do we know where to place the file within it's relative path?  I will continue to work on #272 which would expect a `package.json`.  

otherwise, if there is no package.json, should we always just push to the relative root of the appropriate path?  seems like a rare case when there would be no package.json, anyhow.

**Comment by johnnyman727** [comment]
@rwaldron or @LinusU might be able to comment better than I, but my understanding was that they wanted this so that they can deploy a single script w/o a package.json. I agree that it's not that common but perhaps it's useful for new people who don't know much about Node?

**Comment by wprater** [comment]
perhaps, but the `t2 init` would solve this.. and some sort of package meta
data seems to be required (at least very helpful).  maybe we can have
another sandbox for testing single scripts for testing or single file
deploy?

**Comment by LinusU** [comment]
I want to use it as in the example in my first post. Just pushing one single file and running that.

```sh
cat test.js | ssh root@10.0.43.61 'cat > /tmp/remote-script/test.js; cd /tmp/remote-script; node test.js'
```

I don't think that `t2 init` solves this since the point is to be able to push a file without setting anything up. I also think that scaffolding usually is a bad solution, I don't know how much `t2 init` doest but I would rather just create a `package.json` by myself until I know exactly what it does; no magic... Just my two cents.

**Comment by johnnyman727** [comment]
Fixed with https://github.com/tessel/t2-cli/pull/311
