### ISSUE TITLE
Add support for .tesselinclude file 

### ISSUE THREAD

**Issue by HipsterBrown** [tessel/t2-cli#433]
There is currently support for a `.tesselignore` file that is used in the bundling process before pushing code to Tessel. Also, when the `--slim` flag is used (by default), we follow the dependency graph to pull in only the required, javascript files. 

The default behavior now ignores any non-js assets, i.e. html, css, & images, that the project needs to run. If we can resolve this issue by adding support for a `.tesselignore` file, much like [`.npminclude`](https://github.com/npm/npm/commit/a3ad5cd2a70e1befc82fb433a3c9cb4843ea1d31). 

Use cases:

- Serving a web app from a server running on Tessel. 
- With the `ambient` module, we include a .hex file which is read by `fsReadSync` to reflash the module if the firmware is old

**Comment by rwaldron** [comment]
It's concerning to me that there is no documentation here: https://docs.npmjs.com/misc/developers, where `.npmignore` is documented. The commit you linked to is from 2010 and doesn't do much to shed light on the inclusion semantics, eg. what happens if there is a conflict between `.tesselignore` and `.tesselinclude`? I would assume that the latter wins—which means that `.tesselinclude` _must_ always be processed before `.tesselignore`, so that `.tesselignore` rules that conflict with `.tesseliclude` rules are negated _before_ the browserify bundler object calls `exclude`. Also, nested `.tesselinclude` files need to be respected as well. 

I have a pretty good idea of how this would be integrated for both the `--full` and `--slim` path and would like to take on the assignment—what do you think @HipsterBrown?

**Comment by johnnyman727** [comment]
This will also partially alleviate https://github.com/tessel/t2-cli/issues/423.

**Comment by rwaldron** [comment]
Why partially?

**Comment by johnnyman727** [comment]
Because I think newer users wouldn't know that they have to add any non-included files to a special `.tesselinclude` file or else they won't be deployed. I think they'll expect everything in their project to be deployed.

**Comment by HipsterBrown** [comment]
@rwaldron might be worth making an issue in the npm repo for documenting the use case and internals of `.npminclude`. 

I agree that the latter would win since if the default case for bundling is the `--slim` path, then the `.tesselinclude` file lists the exceptions to that path. With the `--full` path, I'm not sure where the `.tesselinclude` would be useful. 

You did a stellar job implementing the `--slim` path so it'd be rad to see how you accomplish this. Let me know if I can help in any way.

**Comment by rwaldron** [comment]
Great, I'll get started today. I'll need reviewing, smoke tests, etc. will ping you w/ questions along the way.

**Comment by rwaldron** [comment]
https://github.com/npm/docs/issues/438
