### ISSUE TITLE
Latest cli not working with Node 0.12

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#467]
Any time I ran a `t2` command (or `npm install`) I got this:

```sh
➜  t2-cli git:(kb-wifi) ✗ npm install

> t2-cli@0.0.7 postinstall /Users/kelseybreseman/Code/t2-cli
> t2 install-drivers || true

/Users/kelseybreseman/Code/t2-cli/lib/tessel/deploy.js:608
        var shellScript = tags.stripIndent `
                                           ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/kelseybreseman/Code/t2-cli/lib/tessel/tessel.js:119:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/kelseybreseman/Code/t2-cli/lib/lan_connection.js:17:14)
    at Module._compile (module.js:460:26)
➜  t2-cli git:(kb-wifi) ✗ node -v
v0.12.4
```

Upgraded to Node 4.2.2, problem disappeared.

**Comment by rwaldron** [comment]
I don't think this is a bug, t2-cli should stick with node lts at _minimum_

**Comment by johnnyman727** [comment]
@rwaldron if that's the case, we should update the `engine` property of the package.json so it shows a warning on `npm install` if your Node version is too old.

**Comment by sidwarkd** [comment]
Also confirmed it works on Node v5.1.0

**Comment by LinusU** [comment]
@rwaldron Node 0.12 is in active LTS until april 2016

https://medium.com/@nodesource/essential-steps-long-term-support-for-node-js-8ecf7514dbd

**Comment by Student007** [comment]
@LinusU I think we should be strongly oriented by LTS. Also before the `t2-cli` is releasing version `1.0` we should review what is deprecated (I saw some things - I mean). The final step before it is `1.0` could be to modernize all the code parts matching what is possible by LTS limits of that date. 

All further release planing should have a plan related and pointing on LTS and deprecated code reviews.

Because of the limit is the `being familiar with new features` and `knowing about something is deprecated`: 

One skilled **team member** could setup a tutorial for steps to do - I mean, every time a new release is planed as @johnnyman727 is doing - this tutorial could be part of it each time a new LTS/deprecated border is arriving us. 

**That way it would be motivating, reasonable and efficiently.**
( @Frijol It would be a planed organization learning process and is a trigger for reactivating members)

@rwaldron could change the lint rules by that trigger.

So long my two cents...

**Comment by rwaldron** [comment]
@linusu I had totally forgotten about that. Regardless, I recommend that we establish 4.2.1 as the minimum version. I don't think it's unreasonable, considering it's trivial to use nvm to install multiple versions of node.js.

**Comment by LinusU** [comment]
I agree, that gives us lots of room for improving the code base! 👏

**Comment by LinusU** [comment]
@rwaldron Seems like it's only [until 31 december 2015 now](https://nodejs.org/en/blog/release/v0.12.8/)

**Comment by rwaldron** [comment]
@LinusU I think that settles it then :)

**Comment by johnnyman727** [comment]
This issue is pretty much replaced by #470.
