### ISSUE TITLE
Inconsistent working directory for t2 push/run

### ISSUE THREAD

**Issue by flaki** [tessel/t2-cli#544]
The default working directory is inconsistent between `push`-ing and `run`-ning a project.
`process.cwd()` is `/root` instead of the project directory -- but only when using `t2 run`, `t2 push` sets it to the app directory (currently `/app/remote-script`).

**Comment by johnnyman727** [comment]
@flaki interesting find! My guess is that this is probably because when we `run` a command, we just call `node /tmp/remote/script/` but when we `push`, we actually [`cd` into the `\app` directory first](https://github.com/tessel/t2-cli/blob/master/lib/tessel/deploy.js#L791-L795). I think the right way to fix this is to remove the `cd` and just execute the absolute path.

**Comment by rwaldron** [comment]
@flaki if you want to do the fix: https://github.com/tessel/t2-cli/blob/master/lib/tessel/deploy.js#L793

Likely needs updates in tests as well

**Comment by flaki** [comment]
Haha thanks @johnnyman727/@rwaldron, started looking into it! ;)

(also, I was AFK few days, and now that I returned I kept staring at the promise rejection you both link to and was like "how the hell are those two related??", then realized the tree must've changed since, and indeed it did :D https://github.com/tessel/t2-cli/blob/2837f6c3364077fb840ef7f536f174e8bd4200bd/lib/tessel/deploy.js#L793 )

Started this in [deploy-run-cd](/flaki/t2-cli/tree/deploy-run-cd), I'll send the PR when I had the chance making sure all the tests are working properly still.

**Comment by johnnyman727** [comment]
Sorry about that confusion! Code is moving fast around here. :clap:
