### ISSUE TITLE
t2 wifi fails if not connected to wifi

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#611]
I ran `t2 wifi` just to verify that my Tessel was not connected to wifi and I got this error:

```
➜  t2-cli git:(master) t2 wifi
INFO Looking for your Tessel...
INFO Connected to Tessel-02A30958C11A.
ERR! Error: Command failed: Not found
```

To reproduce, just disconnect your Tessel from wifi (`t2 wifi --off`) and then run `t2 wifi`.

**Comment by johnnyman727** [comment]
Clarification: it actually throws that error for any `wifi` command. For example, if I run `t2 wifi --off` and then `t2 wifi -n SSID -p PASS`, it will throw that same error and then successfully connect to the network.

**Comment by HipsterBrown** [comment]
Maybe @rwaldron's latest PR, #610, will help with this. Will try it out during my smoke test tonight.

**Comment by johnnyman727** [comment]
@HipsterBrown I was able to repro on `master` and Rick's branch for #610 (encountered when I was smoke testing) so I think it's unrelated.

**Comment by HipsterBrown** [comment]
@johnnyman727 OK. Will investigate as a separate issue then.

**Comment by HipsterBrown** [comment]
What is the expected output of `t2 wifi` after `t2 wifi --off`? 

I've fixed the issue where enabling a wifi connection, either through `t2 wifi --on` or `t2 wifi -n SSID -p PASS`, would return `ERR! Error: Command failed: Not found` even though the network would successfully connect. I'm still running into that same error with `t2 wifi` but I think it's the expected output since the wifi-iface is disabled.

**Comment by johnnyman727** [comment]
I think at some point, we'll want to intercept the `Command failed: Not found` error and turn it into something that's more understandable for the consumer. Something like "Tessel is not connected to a network." would be a more reasonable message to spew out.
