### ISSUE TITLE
t2 erase output shows reference to 'tessel' instead of 't2'

### ISSUE THREAD

**Issue by dudleyjosh** [tessel/t2-cli#627]
When you do `t2 erase` the output shows `WARN No files have been pushed. Run tessel push FILE to push to Flash.` where `Run tessel push FILE` should be `Run t2 push FILE`.

**Comment by johnnyman727** [comment]
Thanks for finding this @dudleyjosh! Do you want to take the pleasure of making the change?

**Comment by dudleyjosh** [comment]
Sure @johnnyman727... is it just line 28 of `lib/tessel/erase.js` that needs updated? You will have to walk me through the steps needed to actually submit the change.

**Comment by johnnyman727** [comment]
Yes, that's the only piece of code that needs to change. The Github part is a little more involved. Here is a full walkthrough:

1. Click the fork button on the top right of the repository and Github will make a copy of the repo that *you* own. You would not need to do this if you were one of the owners of the `tessel` organization. I can add you to the org but I figure it's better if you learn the hard way first :)

2. If you do not already have the repository cloned, go ahead and clone your repo. You can find your repo at github.com/dudleyjosh/t2-cli after you have forked it and can clone it with `git clone https://github.com/dudleyjosh/t2-cli.git`. If you have already cloned the t2-cli owned by `tessel`, go to step 2.5.

2.5. You will need to add your `t2-cli` repo as a remote endpoint that you can push and pull code from because you don't have permission to push code to the `tessel` owned `t2-cli`. You can do it with this command within your existing `t2-cli` local directory with the command `git remote add dudleyjosh https://github.com/tessel/t2-cli.git`. This says, "Add a new remote endpoint with the name `dudleyjosh` (you can name it something else if you want.

3. Create a new branch to make your changes in. You can do this with `git checkout -b jd-erase-log-fix`. This says create a new branch and name it `jd-erase-log-fix`. I generally name branches with my initials (or just `jon` since it's short) followed by a rather verbose description of what the branch does.

4. Make your changes as you mentioned above.

5. Add those files to the staging area (changes ready to be pushed up) with `git add PATH_TO_CHANGED_FILE` (which in this case will probably be `lib/tessel/erase.js` depending on where you're running this command from).

6. Push those files to your endpoint with `git push dudleyjosh jd-erase-log-fix`. This says please push the staged changes in branch `jd-erase-log-fix` to the endpoint named `dudleyjosh`.

7. The rest of the steps take place on the Github website. Go to the [`t2-cli` PR page](https://github.com/tessel/t2-cli/issues) and click "New pull request".

8. Now click the button that says "Compare Across Forks" because your changes are in your own fork of the repo and not within the `tessel/t2-cli` repo. You would not need to do this if you had commit access to the `tessel` org.

9. Now you'll need to use the drop downs to select the proper branches for the base branch and the compare branch. The base branch should be `tessel/t2-cli:master` (and this will likely be the default). You'll need to edit the compare branch to use your fork and your branch (`dudleyjosh/t2-cli:jd-erase-log-fix`).

10. Scroll down and make sure the changes look appropriate (in this case, there should only be one line changed).

11. If it looks good, click the "Create new pull request" button

That should be it! Let me know if those instructions don't work or are confusing.

**Comment by dudleyjosh** [comment]
I think I was able to do it correctly following your steps above... one small step at a time :)

**Comment by johnnyman727** [comment]
Thanks, I'll follow up on the PR!
