### ISSUE TITLE
[list] displays erroneous "Detected a Tessel that may be booting." 

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#668]
```
$ t2 list
INFO Searching for nearby Tessels...
WARN Detected a Tessel that may be booting.
^Crwaldron at nova in ~/clonez/t2-cli on master*
$ t2 provision
INFO Looking for your Tessel...
INFO Connected to Tessel-02A347EF35F2.
INFO Authenticating Tessel with public key...
INFO Tessel authenticated with public key.
rwaldron at nova in ~/clonez/t2-cli on master*
$ t2 wifi -n Bocoup-Legacy -p *********
INFO Looking for your Tessel...
INFO Connected to Tessel-02A347EF35F2.
INFO Wifi Enabled.
INFO Wifi Connected. SSID: Bocoup-Legacy, password: *********, security: psk2
rwaldron at nova in ~/clonez/t2-cli on master*
$ t2 list
INFO Searching for nearby Tessels...
WARN Detected a Tessel that may be booting.
```

**Comment by johnnyman727** [comment]
I'm not sure what the root cause is but we shouldn't be [assuming any USB errors are from booting Tessels](https://github.com/tessel/t2-cli/blob/master/lib/discover.js#L61-L66). Instead we should be using [a control transfer](https://github.com/tessel/t2-firmware/blob/7908ae1760ae5bc5c2055a528a1ad658c87938ca/firmware/usb.c#L377) to gather the boot state like we already do [in the test rig](https://github.com/tessel/t2-test-rig-sw/blob/master/client/tests/discovery/usb_discovery.js#L124-L137).

**Comment by rwaldron** [comment]
I haven't seen this since reporting. Closing until it comes up again

**Comment by LongLiveCHIEF** [comment]
I'm getting it now.

**Comment by bfzgwg4** [comment]
since i updated t2-cli ive been getting this also
