### ISSUE TITLE
[deployment] Issue bundling entire project

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#674]
@rwaldron I thought we had already resolved this particular issue but maybe the details of this deployment are different. I'm trying to deploy from a project subdirectory and it's not including a required module.

Steps to reproduce:
```
mkdir ambient-test; cd ambient-test;
t2 init;
npm install ambient-attx4;
cd node_modules/ambient-attx4/debug;
t2 run index.js
```

Error Message:
```
➜  debug t2 run update.js
INFO Looking for your Tessel...
INFO Connected to Tessel-02A3BBAD6C82.
INFO Building project.
WARN Some assets in this project were not deployed (see: t2 run --help)
INFO Writing project to RAM on Tessel-02A3BBAD6C82 (8.704 kB)...
INFO Deployed.
INFO Running debug/update.js...
module.js:339
    throw err;
    ^

Error: Cannot find module 'attiny-common'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/tmp/remote-script/debug/update.js:1:89)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
```

**Comment by johnnyman727** [comment]
Note: if you run from one directory higher (`t2 run debug/update.js`) which is the root of the ambient-attx4 project, this issue does *not* occur.

**Comment by johnnyman727** [comment]
Even with the `--full` flag it does not deploy `attiny-common` so I'm not sure what's up.

**Comment by johnnyman727** [comment]
I believe this is an issue how modules are resolved with respect to the dependency file structure. My `debug.update.js` script calls `require('attiny-common');` but the directory structure is like this:
```
ambient-test
--node_modules
----ambient-attx4
------debug
--------update.js
----attiny-common
```

I think `attiny-common` is too "high up" to be resolved.

**Comment by rwaldron** [comment]
> I believe this is an issue how modules are resolved with respect to the dependency file structure.

I don't think this is an "issue"...

I would've assumed that this: 

```
mkdir ambient-test; cd ambient-test;
t2 init;
npm install ambient-attx4;
cd node_modules/ambient-attx4/debug;
t2 run index.js
```

...Will logically result in `node_modules/ambient-attx4/` being treated as the project root, because it has a valid package.json it. It will bundle that module up and deploy it. If `debug` has a dependency that's require()'ed, the missing dependency is ignored (which is necessary to avoid massive false-negatives when mips-specific binary modules don't compile for the local environment, but we know will have a pre-compiled binary injected later. My next question is: why would you try to deploy like this? If you want to test a development branch of ambient-attx4: 

```js
mkdir ambient-test; cd ambient-test;
t2 init;
npm install tessel/ambient-attx4#dev-branch;
cp  node_modules/ambient-attx4/debug/index.js index.js;
# edit index.js as necessary
t2 run index.js
```

I've felt no burden or hardships when working on tessel-io, tessel-av, johnny-five or any other module-as-a-dependency-being-tested using this approach.


......

However, when I try your reproduction, this happens: 

```
rwaldron at nova in ~/robotz/ambient-test/node_modules/ambient-attx4/debug
$ t2 run index.js
INFO Looking for your Tessel...
INFO Connected to bishop.
WARN ENOENT: no such file or directory, lstat 'index.js'
```

I will take a look at this asap, but as for the assumption that your deployment should work—that's never going to be possible considering the package.json presence makes "is this a tessel project root directory" ambiguous

**Comment by rwaldron** [comment]
So, the error that I got is totally correct, because there is no index.js in that directory and I've provided no other path information in the entrypoint. 

Even if you did this: 

```
t2 run node_modules/ambient-attx4/debug/update.js
```

The file would be found, but no debug/package.json, so CLI would go up one to ambient-attx4/ where it _would_ find a package.json. Since we've defined the semantics of finding a tessel 2 project as "has a package.json—must be the project root", it will stop there and start bundling. Take a look: 

```
$ t2 run node_modules/ambient-attx4/debug/update.js
INFO Looking for your Tessel...
INFO Connected to bishop.
INFO Building project.
WARN Some assets in this project were not deployed (see: t2 run --help)
INFO Writing project to RAM on bishop (11.776 kB)...
INFO Deployed.
INFO Running debug/update.js... <--- RIGHT HERE
```

See the path: `debug/update.js`? That's from the root of the project that CLI thought it found, which is ambient-attx4. You might say: "so what, `attiny-common` is a dependency of at `ambient-attx4`, so it should be located in `ambient-attx4/node_modules/`, right?"... Not if you're using npm3: 

```
$ tree -L 2
.
├── index.js
├── node_modules
│   ├── ambient-attx4
│   ├── async
│   ├── attiny-common
│   ├── avr-isp
│   └── sync-queue
└── package.json
```

That's why `--full` isn't finding as well. 


The good news, is that if you just tell CLI where your index.js is, it will work :P 

```js
rwaldron at nova in ~/robotz/ambient-test
$ cd node_modules/ambient-attx4/debug;
rwaldron at nova in ~/robotz/ambient-test/node_modules/ambient-attx4/debug
$ t2 run ../../../index.js
INFO Looking for your Tessel...
INFO Connected to bishop.
INFO Building project.
INFO Writing project to RAM on bishop (9.216 kB)...
INFO Deployed.
INFO Running index.js...
I'm blinking! (Press CTRL + C to stop)
```

**Comment by johnnyman727** [comment]
Ah great. Thanks for investigating!
