### ISSUE TITLE
[push] Starting app from Flash does not work occasionally

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#707]
Cross posted from [the Forums](https://forums.tessel.io/t/tessel-2-does-not-start-my-application-with-push/2329/26)

To Reproduce (On Windows 8/10):
```
t2 init
t2 push index.js
```
Expected Results: Blinking LEDs

Actual Results: No Change in LED state

**Comment by rwaldron** [comment]
I'll test this on my Windows machine in the AM

**Comment by rwaldron** [comment]
I tried doing this, but I can't even get t2-cli installed on my Windows 10 right now. I have no idea wtf is going on with Windows

**Comment by johnnyman727** [comment]
@rwaldron how does it fail?

**Comment by rwaldron** [comment]
TBH, it's too much to explain at the moment and I need to force myself to be done for the day. I was walking through the t2-start experience, using garbage shell cmd.exe and `npm install -g t2-cli` and it failed to install. I'll see if the logs still exist, but I have no interest in spending hours looking at a garbage windows machine today. 

In other news, `npm install; npm link` from within a clone of the repo appears to work, but that's using Git Bash. Running `t2 list` shows a Tessel 2 on LAN (it was setup from my MBP), but there is no USB connection to `t2 provision` over.

Also, I was updated to the preview build that has Bash, so that's pretty cool. I haven't tried it yet, but I'm sure it's lovely.

**Comment by johnnyman727** [comment]
It has been suggested [here](https://forums.tessel.io/t/tessel-2-does-not-start-my-application-with-push/2329/32) that the best way to fix is by adding a `/etc/init.d/tessel-app enable` command to the deploy sequence before attempting to [`/etc/init.d/tessel-app start`](https://github.com/tessel/t2-cli/blob/4345502a66d7758a95428a555736ee41271b0058/lib/tessel/deploy.js#L1074).

**Comment by smrq** [comment]
Can confirm: I was running into this issue.  Just running `t2 push index.js` alone wasn't causing the app to run on boot.  After doing the following manually, the app now runs on boot.

```sh
λ t2 root

...

root@tessel:~# /etc/init.d/tessel-app enable
root@tessel:~# /etc/init.d/tessel-app start
```

**Comment by johnnyman727** [comment]
#752 should fix this.
