### ISSUE TITLE
update-notifier is second worst cause of crashes

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#714]
- 11: http://crash-reporter.tessel.io/crashes?fingerprint=-0x20c7a96f
- 6: http://crash-reporter.tessel.io/crashes?fingerprint=-0x115ae372
- 5: http://crash-reporter.tessel.io/crashes?fingerprint=-0x17165b05
- 2: http://crash-reporter.tessel.io/crashes?fingerprint=-0x1c1fc797
- 1: http://crash-reporter.tessel.io/crashes?fingerprint=-0x10ad46c6
- 1: http://crash-reporter.tessel.io/crashes?fingerprint=-0x17b44ab4

**Comment by rwaldron** [comment]
Related: https://github.com/yeoman/configstore/issues/6

**Comment by johnnyman727** [comment]
@LinusU this is entirely your fault 😄

**Comment by rwaldron** [comment]
FYI, there are a lot more of these

**Comment by LinusU** [comment]
Whoa, that's too bad :(

I wonder why the users don't have access to something in their own home directory that probably wasn't there before...

Hmm, I'm going to do some digging...

**Comment by jimbojw** [comment]
> I wonder why the users don't have access to something in their own home directory that probably wasn't there before...

I have a hunch that it's because `t2 install-drivers` has to be run as root. Looking in my own `.config/configstore` there are other files, but the only one that requires root to access is `update-notifier-t2-cli.json`:

```sh
$ ls -al ~/.config/configstore/
total 20
drwxrwxr-x  2 jimbo jimbo 4096 May 10 06:11 .
drwx------ 37 jimbo jimbo 4096 Mar  5 19:08 ..
-rw-rw-r--  1 jimbo jimbo   36 Jun 15  2014 insight-bower.yml
-rw-------  1 jimbo jimbo   45 Jun 15  2014 update-notifier-bower.yml
-rw-------  1 root  root    55 May 10 06:11 update-notifier-t2-cli.json
```

Per discussion in #727, install-drivers appears to be simplifiable to a pair of shell commands that would not require running node as root.

**Comment by jimbojw** [comment]
Also, FYI, users can't even currently discover that this is their problem because the output of crash reporter doesn't give them a fingerprint.

```sh
$ t2 list
INFO Crash Reported: http://crash-reporter.tessel.io/
```

I understand that #730 / #696 addresses this, but until they're released it requires source code hacking to even find the keywords to search for. This is a blocking issue for Ubuntu users.

**Comment by rwaldron** [comment]
@jimbojw I've released 0.0.20 which now prints out the crash reporter url. We're going to try this before making crash reporter 100% opt-in.

**Comment by jimbojw** [comment]
@rwaldron Thanks! I'll give it a try tomorrow morning.

**Comment by johnnyman727** [comment]
It's worth noting that the `update-notifier` package has been updated to [workaround the permissions issue](https://github.com/yeoman/update-notifier/pull/79) that prints out a banner to encourage people to change config file permissions. We can consider bumping our dependency to that version.

It still doesn't fix the root problem of people running `sudo npm install -g t2-cli`. I think that's fixed with better docs on the install page.
