### ISSUE TITLE
is-root as a third party module dependency is unnecessary

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#747]
This:

```js
'use strict';
module.exports = function () {
	return process.getuid && process.getuid() === 0;
};
```

...Doesn't pay for itself.

**Comment by HipsterBrown** [comment]
Is the solution to replace it with an internal modules, i.e. `lib/is-root.js`? Could this be a good starter issue for a new contributor?

**Comment by rwaldron** [comment]
Or just...

```js
const isRoot = process.getuid && process.getuid() === 0;
```

**Comment by LinusU** [comment]
> Doesn't pay for itself.

What does it cost? Is it really a good idea to start copy and pasting in third party dependencies instead of relying on npm to fetch them for us?

I think that this is a very good writeup on why small modules is a great way to do things: https://github.com/sindresorhus/ama/issues/10#issuecomment-117766328

I think it's better to go in the opposite direction then what this issue is proposing, more things that we can have in separate modules means less things for us to maintain. When an edge case is introduced in how to check for the root user, we don't have to go and update our code to reflect that, it's all done in one place.

I don't think that we should focus on how many lines of code this specific function is, but rather see that it is one specific function that we want, and we don't need to concern ourselves with how it's implemented. By using the `is-root` package, we don't need to know the nitty gritty of how uid:s work on unix.

Also, `is-root` has about half a million downloads a month, and the feeling I'm getting from the community is that we are moving towards small focused modules, following the unix philosophy.

**Comment by rwaldron** [comment]
This has always been, and always will be, a subjective matter. Most of the evidence cited to support small modules can also be interpreted as against—but again, that's subjective. I'm going to close this because I don't really care to argue about it.
