### ISSUE TITLE
AP/WIFI check password validity for encryption type

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#760]
OpenWRT will silently fail if you try to set the password on an access point (or wifi connection but that's less of an issue) to something that is not valid for the encryption type. For example, I tried to create an access point with the encryption type of `psk2` and the password of `stones` but that password was not long enough to be valid. The CLI reported that it was set correctly but the network was never created.

Ideally, we should be able to check for password-encryption validity before we attempt to set it in OpenWRT. The CLI should WARN the user if it is invalid and abort.

**Comment by HipsterBrown** [comment]
This is a great addition @johnnyman727. I have also been looking into this OpenWRT recipe to fallback to ap/wifi only, if one of those configs fail -> https://forum.openwrt.org/viewtopic.php?pid=309131#p309131

These another method of doing that through **Step 3** of this OpenWRT recipe -> http://wiki.openwrt.org/doc/recipes/ap_sta

**Comment by HipsterBrown** [comment]
For anyone who wants to claim this issue:

- [ ] **claim it by commenting below**
- [ ] **add AP password validation** by checking out [`lib/controller.js`](https://github.com/tessel/t2-cli/blob/master/lib/controller.js#L697). If a `password` exists, validate it based on the passed in `security` option. `wpa` and `wpa2` should be removed from the `securityOptions` array as well, since we don't have support for WPA Enterprise right now. 
- [ ] **add tests** for the various password validations
- [ ] **open a PR**

You can find out more about the password validation for the various security options, check out:
- `wep`: http://compnetworking.about.com/od/wirelessfaqs/f/wep_keys.htm
- `psk/psk2`: https://en.wikipedia.org/wiki/Wi-Fi_Protected_Access#Target_users_.28authentication_key_distribution.29

Feel free to ping me for review or questions.

**Comment by smilin-desperado** [comment]
Just saw this on @yourfirstpr. I'd love to give it a try

**Comment by smilin-desperado** [comment]
@HipsterBrown Been too busy to work on this recently and I'm not sure when I will have more time so I will have to 'unclaim' the issue so someone else can have a go at it.

**Comment by HipsterBrown** [comment]
@smilin-desperado Thanks for giving it a shot anyway and letting me know about unclaiming it. Please reach out if you ever want to contribute again in the future. :smile:

**Comment by laiedwin** [comment]
I'd love to take a stab at this!

**Comment by HipsterBrown** [comment]
@laiedwin Awesome, thanks! It's all yours! Feel free to reach out if you have any questions or want me to review.

**Comment by laiedwin** [comment]
Hi @HipsterBrown , I've opened PR #792 for this.

Few things I'm not entirely sure about:
* Is using `var` preferred over the es6-style `let`/`const`? 
* Are my tests in the right place?

Feel free to let me know if there's any changes I should make!

**Comment by HipsterBrown** [comment]
@laiedwin Ok I'll review that today and add feedback to that PR.
