### ISSUE TITLE
Error on init without provision

### ISSUE THREAD

**Issue by jasoniangreen** [tessel/t2-cli#796]
```
ERR! Error writing preference cli.entrypoint index.js
ERR! Error: ENOENT: no such file or directory, open '/Users/jasoniangreen/.tessel/preferences.json'
```

**Comment by johnnyman727** [comment]
Thanks for reporting this @jasoniangreen!

To add more detail, @jasoniangreen ran `t2 run` before running `t2 provision`. Because we have historically create the `~/.tessel` folder when `provision` is run, the `preferences.json` file used by the Crash Reporter was never created.

I believe the solution is to create the `~/.tessel` folder upon install or when *any* command is run.

**Comment by rwaldron** [comment]
Or on install.
